### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by AuroraCampanelli** [phosphor-icons/web#14]
I'm new to this library and I need the npm code to update to the last version that has been relased yesterday beacause most of my icons are not working. Thanks

**Comment by rektdeckard** [comment]
Can you provide an example of how you are using the library? Some APIs have changed since moving from `phosphor-icons@1.4.2` -> `@phosphor-icons/web@2.0.0`, but current usage is documented in our [README](https://github.com/phosphor-icons/web#readme).

**Comment by ThatOneCalculator** [comment]
I think OP's moreso referring to that you need to change how you put your icons in.

It used to be `<i class="ph-house-bold">`, but now it's `<i class="ph-house ph-bold">`.

**Comment by rektdeckard** [comment]
I consider that change well-documented, and under a major version bump and new package name. There's no way to have been accidentally upgraded by not specifying a version via CDN or by updating NPM dependencies,  so I'm marking as closed!
