### ISSUE TITLE
Fill and Duotone Not Working

### ISSUE THREAD

**Issue by Garrett-Gizen** [phosphor-icons/web#19]
Hello, 

When I try to use the universal script or even the direct CSS, all icons that have fill and duotone do not work but all other weights do. Any ideas?

**Comment by rektdeckard** [comment]
I suspect it has to do with a bug in the `woff2` font format that was added as the default yesterday. These weights were working before the change. I will revert and publish to unblock you while I figure it out. cc @ThatOneCalculator

**Comment by ThatOneCalculator** [comment]
Before you revert, let me see if I can figure it out really quick

**Comment by ThatOneCalculator** [comment]
See #20

**Comment by rektdeckard** [comment]
Published and verified working in v2.0.3 @Garrett-Gizen 
https://stackblitz.com/edit/js-2nfd7z?file=index.html,index.js
