### ISSUE TITLE
ERROR: No loader is configured for ".svg" files

### ISSUE THREAD

**Issue by eunukasiko** [phosphor-icons/web#21]
Since upgrading to v2, I'm getting this error:
```
[vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@phosphor-icons/web/src/bold/style.css:6:8: ERROR: No loader is configured for ".svg" files: node_modules/@phosphor-icons/web/s
rc/bold/Phosphor-Bold.svg#Phosphor-Bold
    at failureErrorWithLog (/home/user/project/node_modules/esbuild/lib/main.js:1636:15)
    at /home/user/project/node_modules/esbuild/lib/main.js:1048:25
    at /home/user/project/node_modules/esbuild/lib/main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (x2)
```
Any advice?

**Comment by rektdeckard** [comment]
We ship the icon fonts in 4 formats: .woff2, .woff, .ttf, and .svg (sprite sheet). These are normally resolved in browser at runtime, with the browser choosing the first valid format it supports.

It appears Vite is trying to resolve the imports statically from the CSS file (in this case, the font files in the @font-face directive), but you do not have it configured to resolve SVG modules. I would start by following the guide here to set it up to do that: https://vitejs.dev/guide/features.html#client-types

The annoyance is that this is totally valid CSS on its own, and works directly in the browser. SVG fonts are rare, but supported on all browsers.

**Comment by rektdeckard** [comment]
I assume you are using Vite and TypeScript, but any more info on your setup / framework and steps to reproduce (or a codepen example) would be appreciated.

**Comment by eunukasiko** [comment]
Unfortunately the Vite Client Types didn't work. Spent 2 days trying everything I could think of and couldn't get it to work, so I give up 😅
