### ISSUE TITLE
Icon not named correctly

### ISSUE THREAD

**Issue by emilalsgndr** [phosphor-icons/web#7]
Hi i try using icon fonts with 'https://unpkg.com/phosphor-icons@1.4.1/src/css/icons.css' link at my html. 
When i use 'ph-gear-six' view opens calendar icon. Thats not the same icon.
Here are some screenshoot for explain problem.

<img width="324" alt="Screen Shot 2022-03-03 at 23 32 40" src="https://user-images.githubusercontent.com/100613035/156639330-6bd3fadc-ed0a-4483-ba91-c5446bc897dc.png">
<img width="158" alt="Screen Shot 2022-03-03 at 23 32 55" src="https://user-images.githubusercontent.com/100613035/156639337-bcbe1924-7451-4ac0-a4df-e8675d8f47f7.png">
<img width="482" alt="Screen Shot 2022-03-03 at 23 32 35" src="https://user-images.githubusercontent.com/100613035/156639340-e8a6dba2-e2c5-48fb-9205-c61af9e9c257.png">

**Comment by alsgndremil** [comment]
It happens a lot of icon, not only 'ph-gear-six'

**Comment by rektdeckard** [comment]
This bug has been resolved as of `v2.0.0`.
